name: gits_cli
description: Get it simple command flutter with Gits CLI
homepage: https://gits.id/
repository: https://github.com/gitsindonesia/gits_cli
version: 1.3.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dcli: ^1.36.0
  args: ^2.3.1
  path: ^1.8.3
  yaml: ^3.1.1
  collection: ^1.16.0
  path_to_regexp: ^0.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.1

executables:
  gits_cli: gits_cli
